apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devsecopspipeline
  name: devsecopspipeline
spec:
  replicas: 7
  selector:
    matchLabels:
      app: devsecopspipeline
  template:
    metadata:
      labels:
        app: devsecopspipeline
    spec:
      containers:
        - name: devsecopspipeline
          image: CONTAINERIMAGE
          ports:
            - containerPort: 8080
          env:
            - name: VERSION
              value: CONTAINERIMAGE
            - name: MY_POD_NAME
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
---
apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
  labels:
    app: devsecopspipeline
spec:
  type: LoadBalancer
  selector:
    app: devsecopspipeline
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080