---
version: 0.2

phases:
  install:
    commands:
      - yum update -y && yum -y install curl jq python3-pip python3-dev perl-Digest-SHA && pip3 install --upgrade awscli
      - curl -sS -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/aws-iam-authenticator
      - curl -sS -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/kubectl
      - chmod +x ./kubectl ./aws-iam-authenticator
      - export PATH=$PWD/:$PATH
      - curl -o go1.17.5.linux-amd64.tar.gz https://go.dev/dl/go1.17.5.linux-amd64.tar.gz -vvv -L
      - shasum -a 256 -c <<< 'bd78114b0d441b029c8fe0341f4910370925a4d270a6a590668840675b0c653e  go1.17.5.linux-amd64.tar.gz'
      - rm -rf /usr/local/go && tar -C /usr/local -xzf go1.17.5.linux-amd64.tar.gz
      - export PATH=/usr/local/go/bin:$PATH
      - go version
      - go install github.com/sigstore/cosign/cmd/cosign@latest

  pre_build:
    commands:
      - make ecr_auth
  build:
    commands:
      - make docker_build VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION

  post_build:
    commands:
      - make docker_push VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - make sign VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - make verify VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION
artifacts:
  files: build.json