apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: austin-devsecops-2
  region: us-west-2
nodeGroups:
  - name: ng-1
    instanceType: m5.large
    amiFamily: Ubuntu1804
    desiredCapacity: 3
    ssh:
      allow: true
      publicKeyPath: mac-work
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true