apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: austin-devsecops
  region: us-west-2
  version: "1.16"

nodeGroups:
  - name: regular-node-group
    instanceType: m5.large
    desiredCapacity: 1
    ssh:
      allow: true
      publicKeyPath: mac-work
    tags:
      nodegroup-role: worker
  - name: falco-ubuntu-node-group
    instanceType: m5.large
    ami: ami-0ec78b587b1fe49d7
    desiredCapacity: 1
    ssh:
      allow: true
      publicKeyPath: mac-work
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true