apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: devsecops
  region: us-west-2
  version: "1.21"

nodeGroups:
  - name: node-group-1
    instanceType: m5.large
    desiredCapacity: 3
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true
