---
version: 0.2

phases:
  install:
    commands:
      - make go_version
      - apt-get update && apt-get -y install curl jq python3-pip python3-dev && pip3 install --upgrade awscli
      - curl -o go1.13.5.linux-amd64.tar.gz https://dl.google.com/go/go1.13.5.linux-amd64.tar.gz
      - tar -C /usr/local -xzf go1.13.5.linux-amd64.tar.gz
      - export PATH=${PATH}:/usr/local/go/bin
      - export GOROOT=/usr/local/go
      - go version
  build:
    commands:
      - export PATH=${PATH}:/usr/local/go/bin
      - export GOROOT=/usr/local/go
      - make go_report
  post_build:
    commands:
      - mv devsecopspipeline-*.html devsecopspipeline.html
artifacts:
  files:
    - devsecopspipeline.html
  name: static-code-report