---
version: 0.2

phases:
  install:
    commands:
      - yum -y update && yum install -y install curl jq
      - curl -o go1.17.1.linux-amd64.tar.gz https://dl.google.com/go/go1.17.1.linux-amd64.tar.gz
      - tar -C /usr/local -xzf go1.17.1.linux-amd64.tar.gz
      - export PATH=${PATH}:/usr/local/go/bin
      - export GOROOT=/usr/local/go
      - go version
  build:
    commands:
      - export PATH=${PATH}:/usr/local/go/bin
      - export GOROOT=/usr/local/go
      - make test
      - make go_report
      - make go_sec
  post_build:
    commands:
      - mv src-*.html devsecopspipeline.html
artifacts:
  files:
    - devsecopspipeline.html
    - security.json
  name: static-code-report
reports:
  security-report:
    files:
    - "security.json"
    file-format: "JSON"
