---
version: 0.2

phases:
  install:
    commands:
      - yum -y update && yum install -y install curl jq
      - curl -o go1.17.5.linux-amd64.tar.gz https://go.dev/dl/go1.17.5.linux-amd64.tar.gz -vvv -L
      - shasum -a 256 -c <<< 'bd78114b0d441b029c8fe0341f4910370925a4d270a6a590668840675b0c653e  go1.17.5.linux-amd64.tar.gz'
      - rm -rf /usr/local/go && tar -C /usr/local -xzf go1.17.5.linux-amd64.tar.gz
      - export PATH=/usr/local/go/bin:$PATH
      - go version
  build:
    commands:
      - export PATH=${PATH}:/usr/local/go/bin
      - export GOROOT=/usr/local/go
      - make test
      - make go_report
      - make go_sec
  post_build:
    commands:
      - mv src-*.html devsecopspipeline.html
artifacts:
  files:
    - devsecopspipeline.html
    - security.json
  name: static-code-report
reports:
  security-report:
    files:
    - "security.json"
    file-format: "JSON"
